@startuml
title Bausteinsicht — Ebene 2: Whitebox Kommunikation
skinparam shadowing false
skinparam defaultTextAlignment center
skinparam monochrome true
skinparam ArrowColor #333333
skinparam folderBackgroundColor #ECECEC
skinparam packageStyle rectangle
skinparam linetype ortho
skinparam nodesep 55
skinparam ranksep 70
top to bottom direction
rectangle "Kommunikation  (Whitebox — Ebene 2)" as COM {
  folder "Konversationsverwaltung" as a
  folder "Nachrichtenversand" as b
  folder "Nachrichten Persistenz" as c
}
database "Datenbank" as db

b -down-> c : Echtzeit-Nachricht
a -down-> db
c -down-> db
@enduml
